name: buildahome
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version numbe r is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number
#  may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.13+22

environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  swipedetector: ^1.2.0
  percent_indicator: "^2.1.1"
  photo_view: ^0.5.0
  file_picker: ^4.4.0
  image_picker: 
  image: ^2.1.4
  multi_image_picker: ^4.7.14
  flutter_spinkit: "^4.0.0"
  intl: ^0.15.8
  path_provider: ^1.4.4
  url_launcher: 
  carousel_slider: ^1.3.0
  grouped_buttons: ^1.0.4
  shared_preferences: ^0.5.3+4
  flutter_launcher_icons: "^0.7.0"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.2.0+1
  firebase_messaging: 6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/newlogo.png"
  image_path_android: "assets/newlogo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf
    - family: PatuaOne
      fonts:
        - asset: assets/fonts/PatuaOne-Regular.ttf
    - family: BreeSerif
      fonts:
         - asset: assets/fonts/BreeSerif-Regular.ttf
    - family: SFPro
      fonts:
         - asset: assets/fonts/SF Pro.ttf
    - family: Mulish-Regular
      fonts:
          - asset: assets/fonts/Mulish/Mulish-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
